---
config:
    vagrant:
        box:
            name: box-cutter/centos67
            url: https://vagrantcloud.com/box-cutter/boxes/centos67
        cpus: '2'
        memory: '512'
        network:
            hostmanager: '1'
            private_address: 192.168.33.10
            forwarded_port:
                tcp80:
                    guest: '80'
                    host: '80'
                tcp443:
                    guest: '443'
                    host: '443'
    server:
        hostname: test.dev
        packages:
            - curl
            - libcurl3
            - libcurl3-dev
            - wget
    php:
        install: '1'
        version: '5.5'
        modules:
            - common
            - gd
            - mbstring
            - mcrypt
            - mysql
            - pdo
            - xdebug
            - xml
            - xmlrpc
    mysql:
        install: '1'
        version: '5.6'
        user: root
        pass: root
        db: root
        import:
            - schema.sql
            - data.sql
    apache:
        install: '1'
        user: vagrant
        web_root: '/vagrant/public_html'
        log_dir: '/vagrant/logs'
        modules:
            - php
            - rewrite
            - ssl
    adminer:
        install: '1'
    ftp:
        install: '1'